name: CI/CD

on:
  push:
    branches: [ main ]


permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/cicd-demo:latest
          platforms: linux/amd64,linux/arm64



      # Optional: trigger Railway deploy using CLI (uncomment if you want to automate deploy from Actions)
      # - name: Install Railway CLI
      #   run: curl -sL https://railway.app/install.sh | sh
      #
      # - name: Deploy to Railway (example)
      #   env:
      #     RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }}
      #     RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
      #     RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
      #   run: |
      #     railway login --apiKey "$RAILWAY_API_KEY"
      #     # Use railway CLI commands to deploy or update services as needed.
